network:
  layers: [30, 20, 10, 5]
  learning_rate: 0.1
  beta: 0.5
  function: "tan_h"
  optimizer: "adam"
best_networks:
  - net1:
      layers: [30, 20, 10, 5]
      learning_rate: 0.0001
      beta: 0.5
      function: "tan_h"
      optimizer: "adam"
train: False
new_letter:
  generate: False
  x: 0.76
  y: 0.7
