network:
  layers: [30, 20, 10, 4]
  learning_rate: 0.01
  beta: 0.5
  function: "tan_h"
  optimizer: "adam"
best_networks:
  - net1:
      layers: [30, 20, 10, 5]
      learning_rate: 0.0001
      beta: 0.5
      function: "tan_h"
      optimizer: "adam"
run_config:
  train: False
  continue: True
test_alphabet:
  generate: False
new_letter:
  generate: True
  x: -1.3
  y: -0.2
denoising:
  enable: False
  noise_type: "gaussian" # "gaussian" or "salt_and_pepper"
  noise_level: 0.1
variational:
  enable: True
